// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDtNW_Xi_plrkJvt__hfDwFVX8569oDk',
    appId: '1:422986535519:web:5f0727ce2c1946fffe01ea',
    messagingSenderId: '422986535519',
    projectId: 'recicla-31728',
    authDomain: 'recicla-31728.firebaseapp.com',
    storageBucket: 'recicla-31728.appspot.com',
    measurementId: 'G-QRRSHZXPYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQNvQ_FQHVhpu1xCeUSK9JMjhYIrFt7c',
    appId: '1:422986535519:android:299ec5075d1e7d6cfe01ea',
    messagingSenderId: '422986535519',
    projectId: 'recicla-31728',
    storageBucket: 'recicla-31728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7zWd_gpbOGhaEUTlr-6oY8oct6SYatU',
    appId: '1:422986535519:ios:6a683fc59c6e1cbefe01ea',
    messagingSenderId: '422986535519',
    projectId: 'recicla-31728',
    storageBucket: 'recicla-31728.appspot.com',
    iosBundleId: 'com.example.recicla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ7zWd_gpbOGhaEUTlr-6oY8oct6SYatU',
    appId: '1:422986535519:ios:39a50357adc3f5adfe01ea',
    messagingSenderId: '422986535519',
    projectId: 'recicla-31728',
    storageBucket: 'recicla-31728.appspot.com',
    iosBundleId: 'com.example.recicla.RunnerTests',
  );
}
